-- migrate:up

BEGIN;

SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `team` DROP COLUMN `description3`;
ALTER TABLE `team` CHANGE COLUMN `name` `name` VARCHAR (64) NOT NULL;
ALTER TABLE `event` CHANGE COLUMN `name` `name` VARCHAR (64) NOT NULL;

SET FOREIGN_KEY_CHECKS = 1;

COMMIT;

-- migrate:down

BEGIN;

SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `event` CHANGE COLUMN `name` `name` VARCHAR (255) NOT NULL;
ALTER TABLE `team` ADD COLUMN `description3` LONGTEXT COMMENT '描述' AFTER `description`;
ALTER TABLE `team` CHANGE COLUMN `name` `name` VARCHAR (255) NOT NULL;

SET FOREIGN_KEY_CHECKS = 1;

COMMIT;