"""First create user add role table 22

Revision ID: b9c1746484ce
Revises: 84f78a54d038
Create Date: 2020-05-05 05:14:22.558462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c1746484ce'
down_revision = '84f78a54d038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
