# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailCfilterRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='\u7ba1\u7406\u5458\u8f93\u5165\u7684\u89c4\u5219\u5907\u6ce8\uff0c\u53ef\u4e0d\u586b', max_length=150, null=True, verbose_name='\u89c4\u5219\u540d\u79f0')),
                ('type', models.IntegerField(choices=[(-1, '\u5916\u53d1'), (1, '\u63a5\u6536')], default=-1, verbose_name='\u7c7b\u578b')),
                ('logic', models.CharField(choices=[(b'all', '\u6ee1\u8db3\u6240\u6709\u6761\u4ef6'), (b'one', '\u6ee1\u8db3\u4e00\u6761\u5373\u53ef')], default='all', help_text='all\uff1a\u6ee1\u8db3\u6240\u6709\u6761\u4ef6\uff0cone\uff1a\u6ee1\u8db3\u4e00\u6761\u5373\u53ef', max_length=50, verbose_name='\u6761\u4ef6\u5173\u7cfb')),
                ('sequence', models.IntegerField(default=999, verbose_name='\u89c4\u5219\u4f18\u5148\u7ea7')),
                ('disabled', models.IntegerField(choices=[(-1, '\u542f\u7528'), (1, '\u7981\u7528')], default=-1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'mail_cfilter',
            },
        ),
        migrations.CreateModel(
            name='MailCfilterRuleAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(db_index=True, default=0, help_text='\u6240\u5c5e\u8282\u70b9\uff0cext_cfilter_rule_new\u7684\u4e3b\u952e', verbose_name='\u6240\u5c5e\u89c4\u5219')),
                ('action', models.CharField(choices=[(b'break', '\u4e2d\u65ad\u6267\u884c\u89c4\u5219'), (b'jump_to', '\u8df3\u8fc7\u540e\u9762N\u4e2a\u89c4\u5219'), (b'flag', '\u8bbe\u7f6e\u65d7\u5e1c'), (b'label', '\u8bbe\u7f6e\u6807\u7b7e'), (b'delete', '\u5220\u9664\u90ae\u4ef6'), (b'sequester', '\u9694\u79bb\u90ae\u4ef6'), (b'move_to', '\u79fb\u52a8\u90ae\u4ef6\u81f3\u6587\u4ef6\u5939'), (b'copy_to', '\u590d\u5236\u90ae\u4ef6\u81f3\u6587\u4ef6\u5939'), (b'forward', '\u8f6c\u53d1'), (b'delete_header', '\u5220\u9664\u90ae\u4ef6\u5934'), (b'append_header', '\u8ffd\u52a0\u5934\u90e8'), (b'append_body', '\u8ffd\u52a0\u90ae\u4ef6\u5185\u5bb9'), (b'mail', '\u53d1\u9001\u90ae\u4ef6')], max_length=50, verbose_name='\u52a8\u4f5c')),
                ('value', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u503c')),
                ('sequence', models.IntegerField(default=999, verbose_name='\u52a8\u4f5c\u4f18\u5148\u7ea7')),
            ],
            options={
                'db_table': 'mail_cfilter_action',
            },
        ),
        migrations.CreateModel(
            name='MailCfilterRuleOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(db_index=True, default=0, help_text='\u6240\u5c5e\u8282\u70b9\uff0cext_cfilter_rule_new\u7684\u4e3b\u952e', verbose_name='\u6240\u5c5e\u89c4\u5219')),
                ('parent_id', models.IntegerField(db_index=True, default=0, help_text='\u8fd9\u4e2a\u6761\u4ef6\u7684\u7236\u4eb2ID\uff0c\u903b\u8f91\u5173\u7cfb\u7531parent_id\u6307\u5411\u7684\u90a3\u4e00\u884c\u51b3\u5b9a', verbose_name='\u7236ID')),
                ('logic', models.CharField(choices=[(b'all', '\u5e76'), (b'one', '\u6216')], default='all', help_text='all:\u5e76\u4e14,one\uff1a\u6216', max_length=50, verbose_name='\u903b\u8f91\u8868\u8fbe\u5f0f')),
                ('option', models.CharField(choices=[(b'header', '\u90ae\u4ef6\u5934'), (b'extra', '\u5176\u4ed6')], max_length=50, verbose_name='\u6761\u4ef61')),
                ('suboption', models.CharField(max_length=50, verbose_name='\u6761\u4ef62')),
                ('action', models.CharField(choices=[(b'contains', '\u5305\u542b'), (b'not_contains', '\u4e0d\u5305\u542b'), (b'==', '\u7b49\u4e8e'), (b'>=', '\u5927\u4e8e\u7b49\u4e8e'), (b'<=', '\u5c0f\u4e8e\u7b49\u4e8e'), (b'in', '\u5c5e\u4e8e'), (b'not_in', '\u4e0d\u5c5e\u4e8e')], max_length=50, verbose_name='\u52a8\u4f5c')),
                ('value', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u503c')),
            ],
            options={
                'db_table': 'mail_cfilter_option',
            },
        ),
    ]
