# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, help_text='\u53ef\u9009\u9879\uff0c\u82e5\u4e3a\u7a7a\u5219\u6458\u53d6\u6b63\u6587\u94b154\u4e2a\u5b57\u7b26', null=True, verbose_name='\u6458\u8981'),
        ),
    ]
