# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171221_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKeditorPictureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(db_index=True, default=0, verbose_name='\u6587\u7ae0ID')),
                ('filename', models.CharField(max_length=100, verbose_name='\u56fe\u7247\u540d')),
                ('filetype', models.CharField(max_length=100, verbose_name='\u56fe\u7247\u7c7b\u578b')),
                ('filepath', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='\u6587\u4ef6\u8def\u5f84')),
                ('filesize', models.IntegerField(default=0, verbose_name='\u6587\u4ef6\u5927\u5c0f')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'blog_picture',
            },
        ),
    ]
