# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180107_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6765\u6e90'),
        ),
    ]
