# Generated by Django 2.1.5 on 2019-12-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('name2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名称2')),
                ('email', models.CharField(db_index=True, max_length=50, verbose_name='邮箱')),
                ('order_no', models.CharField(db_index=True, max_length=50, verbose_name='订单号')),
                ('province', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='省/州')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单金额')),
                ('permmisson', models.IntegerField(choices=[(1, '查看'), (2, '编辑')], default=1, verbose_name='权限')),
                ('disabled', models.IntegerField(default=0, verbose_name='模式')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试',
                'db_table': 'test',
            },
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('email', 'order_no')},
        ),
    ]
