# Generated by Django 2.1.5 on 2020-01-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
