# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 13:55
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.IntegerField(default=0, verbose_name='\u5e74\u9f84')),
                ('linkman', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u624b\u673a')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u516c\u53f8')),
                ('gender', models.CharField(choices=[(b'Male', '\u7537'), (b'Female', '\u5973')], default='Male', max_length=10, verbose_name='\u6027\u522b')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4e2a\u4eba\u7f51\u5740')),
                ('note', models.TextField(blank=True, null=True, verbose_name='\u4e2a\u6027\u7b7e\u540d')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'db_table': 'core_user',
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(db_index=True, default=0, verbose_name='\u7236ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u540d\u79f0')),
                ('order', models.IntegerField(default=0, help_text='\u90e8\u95e8\u5c55\u73b0\u987a\u5e8f')),
            ],
            options={
                'db_table': 'core_department',
            },
        ),
        migrations.CreateModel(
            name='Prefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u952e')),
                ('value', models.TextField(blank=True, null=True, verbose_name='\u503c')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'core_prefs',
            },
        ),
    ]
