# -*- coding: utf-8 -*-

"""
Django settings for operation project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')ld$-iyr13g_0%rw_^gi+$6y&-52!gj7zhh=%=(b8^#6b!vzc0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ["0.0.0.0", "192.168.1.24"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'goods',
]

# debug_toolbar
INTERNAL_IPS = ('127.0.0.1',) # 测试环境是在本机

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'middleware.x_forwarded_for.XForwardedForMiddleware',
    # 'auditlog.middleware.AuditlogMiddleware',
    # 'middleware.login.MyLoginMiddleware',
]

ROOT_URLCONF = 'spike.urls'
# auth 模块
# AUTH_USER_MODEL = 'core.User'
# 登录url
# LOGIN_URL = '/core/login'
# LOGIN_REDIRECT_URL = '/core/home'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'spike.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'spike',                      # Or path to database file if using sqlite3.
        'USER': 'spike',                      # Not used with sqlite3.
        'PASSWORD': '123456',                  # Not used with sqlite3.
        'HOST': '127.0.0.1',                      # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '3306',                      # Set to empty string for default. Not used with sqlite3.
    },
}

# ---------------------------
# CACHES

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis_master/127.0.0.1:26382,127.0.0.1:26383,127.0.0.1:26384,127.0.0.1:26385/0",
        "LOCATION": "mymaster/127.0.0.1:26382,127.0.0.1:26383,127.0.0.1:26384,127.0.0.1:26385/0",
        "OPTIONS": {
            #"PASSWORD": 's3cret_passw0rd!',
            "CLIENT_CLASS": "django_redis_sentinel.SentinelClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            # "SOCKET_TIMEOUT": 10,
        }
    },
    "db2": {
        "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis_master/127.0.0.1:26382,127.0.0.1:26383,127.0.0.1:26384,127.0.0.1:26385/0",
        "LOCATION": "mymaster/127.0.0.1:26382,127.0.0.1:26383,127.0.0.1:26384,127.0.0.1:26385/1",
        "OPTIONS": {
            #"PASSWORD": 's3cret_passw0rd!',
            "CLIENT_CLASS": "django_redis_sentinel.SentinelClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            # "SOCKET_TIMEOUT": 10,
        }
    }
}
DJANGO_REDIS_CLOSE_CONNECTION=True
REDIS_SENTINEL_DATABASES = [('192.168.1.24', 26382), ('192.168.1.24', 26383), ('192.168.1.24', 26384), ('192.168.1.24', 26385)]
REDIS_SENTINEL_SERVICE_NAME = "mymaster"

# Name of cache backend to cache user agents. If it not specified default
# cache alias will be used. Set to `None` to disable caching.
USER_AGENTS_CACHE = 'default'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

#USE_X_FORWARDED_HOST = True
#FORCE_SCRIPT_NAME = '/operation'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
# MEDIA_URL = os.path.join(BASE_DIR,'media')
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

STATIC_URL = '/static/'
# STATIC_PATH = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    # MEDIA_ROOT,
)


# ---------------------------



