# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0008_logentry_domain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='domain_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='\u6240\u5c5e\u57df\u540dID'),
        ),
    ]
