# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auditlog', '0009_auto_20180612_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditlogContentype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': '\u7edf\u8ba1\u5165\u5e93\u6b64\u5904\u7684content_type_id',
                'verbose_name_plural': '\u7edf\u8ba1\u5165\u5e93\u6b64\u5904\u7684content_type_id',
            },
        ),
        migrations.AddField(
            model_name='logentry',
            name='extend_type',
            field=models.TextField(blank=True, help_text='api\u4f7f\u7528', null=True, verbose_name='\u6269\u5c55\u8bf4\u660e'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='is_extend',
            field=models.BooleanField(default=0, help_text='api\u4f7f\u7528', verbose_name='\u662f\u5426\u662f\u6269\u5c55\u7684\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u6dfb\u52a0'), (1, '\u66f4\u65b0'), (2, '\u5220\u9664')], verbose_name='action'),
        ),
    ]
