# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-12 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0010_auto_20180612_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='extend_content',
            field=models.TextField(blank=True, help_text='api\u4f7f\u7528', null=True, verbose_name='\u6269\u5c55\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='extend_type',
            field=models.CharField(blank=True, choices=[('', '----'), ('login', '\u767b\u5f55'), ('logout', '\u767b\u51fa')], db_index=True, help_text='api\u4f7f\u7528', max_length=50, null=True, verbose_name='\u6269\u5c55\u7c7b\u578b'),
        ),
    ]
